[workspace]
authors = ["JP Calcitrai <jpcalcitrai@gmail.com>"]
channels = ["conda-forge"]
name = "strategic_cyber_defense_simulation"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
numpy = ">=2.4.1,<3"
pandas = ">=3.0.0,<4"
